# NOTE: This pipeline depends on the following variable groups: 

# Name of variable group                  Keys inside variable group
# ----------------------                  --------------------------
# redgate_global_vars                     FLYWAY_LICENSE_KEY, BASELINE_VERSION, FIRST_UNDO_SCRIPT, AGENT_POOL           
# redgate_build_credentials               target_database_JDBC, check_JDBC

# PARELLELISM
# Pay close attention to the "dependsOn" flag - this determines which block follows each other. 
# It's possible to parallelize dpelyments by using multiple agent pools and the "dependsOn" flag.

name: SQLServerCentralBuildPipeline
 
trigger:
  branches:
    include:
      - Development
  paths:
    include:
      - migrations/*

# Move the templates to their own repository for greater control and lack of repitition across projects (DRY)
# They can be included in the same repository if preferred: templates/vars.yml would work for the file below

variables:
- template: vars.yml                            # vars.yml@templates if kept in templates repository

stages:
- template: build.yml                           # build.yml@templates if kept in templates repository
  parameters:
    stage: Build
    displayName: CI Build and Code Validation
    executeBuild: true
    targetCredentials: redgate_build_credentials
    pipelineParameters: redgate_global_vars